INSERT INTO tb_categoria (nome, criado_Em) values ('Livros' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('Eletronicos' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('Computadores' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('Teclados' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('Mouses' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('Notebooks' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('Monitores' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('Processadores' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('Memorias' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('Placa mãe' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('Cooler' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('Walter cooler' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('SSD' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('SSD.M2' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('HD' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('Suporte de monitor' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('Suporte de notebook' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('MousePad' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('MouseBang' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('Web cam' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('Celulares' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('Carregadores portatil' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('Consoles' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('Tablets' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('Cadeiras' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('Fones' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('Televisões' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('Gabinetes' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('Caixa de som' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('Headset' , NOW());
INSERT INTO tb_categoria (nome, criado_Em) values ('SmartWatch' , NOW());